name: Generate PDF
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install xvfb wkhtmltopdf
      - run: xvfb-run --auto-servernum wkhtmltopdf index.html resume.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: Resume
          path: resume.pdf
